name: Build Android APK

on:
  workflow_dispatch:

  push:
    branches:
      - main
    paths:
      - "main.py"
      - "buildozer.spec"
      - ".github/workflows/build.yml"

jobs:
  build:
    name: Build Android APK
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build APK
        uses: ArtemSBulgakov/buildozer-action@v1
        with:
          workdir: .
          command: buildozer android debug

      - name: Show APK files
        run: |
          echo "APK files:"
          find . -type f -name "*.apk" -print

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: YouTube-Downloader-APK
          path: "**/*.apk"
          if-no-files-found: error
          retention-days: 30
